#+title: Pertab
An implementation of dwm's [[http://dwm.suckless.org/patches/pertag/][pertag]] in emacs.

* Installation
Copy pertab somewhere into your loadpath

Add this to your init.el
#+begin_src emacs-lisp
(use-package pertab
  :hook (tab-bar-mode . pertab-mode)
  :custom pertab-default-layout 'manual
  :bind (:map pertab-mode-map
	      ("s-h" . pertab-focus-left)
	      ("s-j" . pertab-focus-down)
	      ("s-k" . pertab-focus-up)
	      ("s-l" . pertab-focus-right)
	      ("s-H" . pertab-move-left)
	      ("s-J" . pertab-move-down)
	      ("s-K" . pertab-move-up)
	      ("s-L" . pertab-move-right)
	      ("s-c" . pertab-horizontal-split)
	      ("s-v" . pertab-vertical-split)
	      ("s-q" . pertab-close-window)
	      ("s-Q" . pertab-kill-buffer-close-window)
	      ("s-y" . pertab-layout-menu)))

(use-package pertab-monocle) ;; If you want the monocle layout.
(use-package pertab-follow) ;; If you want the follow layout.
(use-package pertab-master-stack) ;; If you want either of the master/stack layouts
(use-package pertab-manual) ;; Highly reccomended
(use-package pertab-scroll) ;; For a scrolling layout. Requires roll.el
#+end_src

* Configuration Variables
+ =pertab-default-layout=- the layout to use when creating a new tab
+ =pertab-next-buffer-function=- The function to call when trying to focus a new window downwards or to the right on a tab with only 1 window. Defaults to =next-buffer=.
+ =pertab-previous-buffer-function=- The function to call when trying to focus a new window upwards or to the left on a tab with only 1 window. Defaults to =previous-buffer=.

* Layouts
Each layout provides its own entry & exit hooks. These run when switching tabs, or switching layouts.
** Monocle
+ 1 window is visible at a time. (As seen in dwm).
+ Window navigation commands will always run their next/previous buffer functions
+ Your previous window configuration will be restored after exiting the monocle layout.
+ This module comes from [[https://github.com/dakra/dmacs][Dmacs]].
| Entry Hook                | Exit Hook                | Entry Command      |
|---------------------------+--------------------------+--------------------|
| pertab-monocle-enter-hook | pertab-monocle-exit-hook | pertab-set-monocle |

** Follow
+ A scrolling layout on the focused buffer using follow-mode. Closes all other windows upon entry & restores them upon exit.
+ Any split command will split the focused buffer horizontally.
+ Moving left will focus the window to the left, or scroll the buffer up a page if the leftmost window is focused.
+ Moving right will focus the window to the right, or scroll the buffer up a page if the rightmost window is focused.
| Entry Hook               | Exit Hook               | Entry Command     |
|--------------------------+-------------------------+-------------------|
| pertab-follow-enter-hook | pertab-follow-exit-hook | pertab-set-follow |

** Master/Stack
+ As seen in dwm.
+ Needs [[https://github.com/Fuco1/elwm][elwm]] in order to work.
+ Focusing up or down will move to the previous/next window
+ Splitting the current window will create a new window on the stack.
+ Moving the current window up/down will rotate the windows counterclockwise/clockwise
| Entry Hook                     | Exit Hook                     | Entry Command           |
|--------------------------------+-------------------------------+-------------------------|
| pertab-master-stack-enter-hook | pertab-master-stack-exit-hook | pertab-set-master-stack |

** Master/Stack Horizontal
+ Like master stack, but the master is on the bottom of the screen & the stack is on the top.
+ Needs [[https://github.com/Fuco1/elwm][elwm]] in order to work.
| Entry Hook                                | Exit Hook                                | Entry Command                      |
|-------------------------------------------+------------------------------------------+------------------------------------|
| pertab-master-stack-horizontal-enter-hook | pertab-master-stack-horizontal-exit-hook | pertab-set-master-stack-horizontal |

** Manual
+ A manual tiling window layout, like what is usually used in emacs.
+ Each command should do exactly what it says on the tin.
| Entry Hook               | Exit Hook               | Entry Command     |
|--------------------------+-------------------------+-------------------|
| pertab-manual-enter-hook | pertab-manual-exit-hook | pertab-set-manual |

** Scroll
+ A scrolling layout, like niri.
+ Requires [[https://github.com/finalclass/emacs-roll][roll]], which provides all the important logic.
+ Splitting the window creates a new roll pane.
+ Focusing the window to the left or right scrolls in that direction
+ Moving the current window to the left or right does exactly what you would expect.
| Entry Hook               | Exit Hook               | Entry Command     |
|--------------------------+-------------------------+-------------------|
| pertab-scroll-enter-hook | pertab-scroll-exit-hook | pertab-set-scroll |

* Registering Layouts
To register a new layout, call =pertab-register-layout=. It takes 3 arguments.
1. A symbol, which will be used to refer to the layout manager object
2. An alist of tab-local variables that the layout needs, with their default values.
3. A =pertab-layout-manager= object.

** Example
A scrolling layout, using [[https://github.com/finalclass/emacs-roll][roll]]
#+begin_src emacs-lisp
(pertab-register-layout 'scroll '((roll-max-visible-panes . 2)
				  (roll--windows . ())
				  (roll--panes . ())
				  (roll--nof-visible-panes . 1)
				  (roll--first-visible-pane . 0))
			(pertab-layout-manager :lighter "[]>"
					       :enter-fun 'pertab-scroll-enter
					       :exit-fun 'pertab-scroll-exit
					       :horiz-split-fun 'roll-open
					       :vert-split-fun 'roll-open
					       :focus-left-fun 'roll-go-left
					       :focus-right-fun 'roll-go-right
					       :move-left-fun 'roll-move-left
					       :move-right-fun 'roll-move-right
					       :close-window-fun 'roll-close))
#+end_src

* Credits
+ [[https://github.com/alphapapa/bufler.el][Alphapapa's Bufler]]- This is where I learned how to add metadata to tabs, & I borrowed a couple of the functions he used for doing so.
+ [[https://github.com/dakra/dmacs][Dmacs]]- This is where the monocle layout originates from
