#+title: Pertab
An implementation of dwm's [[http://dwm.suckless.org/patches/pertag/][pertag]] in emacs.

* Installation
Copy pertab somewhere into your loadpath

Add this to your init.el
#+begin_src emacs-lisp
(use-package pertab
  :hook (tab-bar-mode . pertab-mode)
  :custom pertab-default-layout 'monocle)

(use-package pertab-monocle)
#+end_src

* Configuration Variables
+ =pertab-default-layout=- the layout to use when creating a new tab
+ =pertab-next-buffer-function=- The function to call when trying to focus a new window downwards or to the right on a tab with only 1 window. Defaults to =next-buffer=.
+ =pertab-previous-buffer-function=- The function to call when trying to focus a new window upwards or to the left on a tab with only 1 window. Defaults to =previous-buffer=.

* Layouts
+ monocle: 1 window is visible at a time. Restores the former window state after exiting.

* Registering Layouts
To register a new layout, call =pertab-register-layout=. It takes 3 arguments.
1. A symbol, which will be used to refer to the layout manager object
2. An alist of tab-local variables that the layout needs, with their default values.
3. A =pertab-layout-manager= object.

** Examples
A normal, manual tiling layout (like one might be used to in emacs)
#+begin_src emacs-lisp
(pertab-register-layout 'manual '()
			  (pertab-layout-manager :lighter "[+]"
						 :enter-fun 'pertab-manual-enter
						 :exit-fun 'pertab-manual-exit
						 :horiz-split-fun 'split-window-horizontally
						 :vert-split-fun 'split-window-vertically
						 :focus-left-fun 'windmove-left
						 :focus-right-fun 'windmove-right
						 :focus-down-fun 'windmove-down
						 :focus-up-fun 'windmove-up
						 :move-left-fun 'windmove-swap-states-left
						 :move-right-fun 'windmove-swap-states-right
						 :move-down-fun 'windmove-swap-states-down
						 :move-up-fun 'windmove-swap-states-up
						 :close-window-fun 'delete-window))
#+end_src

A scrolling layout, using [[https://github.com/finalclass/emacs-roll][roll]]
#+begin_src emacs-lisp
(pertab-register-layout 'scroll '((roll-max-visible-panes . 2)
				  (roll--windows . ())
				  (roll--panes . ())
				  (roll--nof-visible-panes . 1)
				  (roll--first-visible-pane . 0))
			(pertab-layout-manager :lighter "[]>"
					       :enter-fun 'pertab-scroll-enter
					       :exit-fun 'pertab-scroll-exit
					       :horiz-split-fun 'roll-open
					       :vert-split-fun 'roll-open
					       :focus-left-fun 'roll-go-left
					       :focus-right-fun 'roll-go-right
					       :move-left-fun 'roll-move-left
					       :move-right-fun 'roll-move-right
					       :close-window-fun 'roll-close))
#+end_src

* Credits
+ [[https://github.com/alphapapa/bufler.el][Alphapapa's Bufler]]- This is where I learned how to add metadata to tabs, & I borrowed a couple of the functions he used for doing so.
+ [[https://github.com/dakra/dmacs][Dmacs]]- This is where the monocle layout originates from
